name: test targets workflow

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:
    # branches:
    #   - '*'

jobs:
  test-targets-workflow:
    runs-on: ubuntu-latest
    container: rocker/tidyverse:4.2.3
    env:
      GIT_CRYPT_KEY64: ${{ secrets.GIT_CRYPT_KEY64 }}
      GITHUB_PAT: ${{ secrets.GH_PAT }}
    steps:
      - uses: actions/checkout@v3
      
      - name: Install system dependencies
        run: |
          apt-get update && apt-get install -y --no-install-recommends \
          libxt6 libglpk-dev
          
      - name: Trust git repo
        run: |
          git config --global --add safe.directory /__w/opensci-evaluation/opensci-evaluation
          
      - name: Install packages from renv.lock (with cache)
        if: ${{ !env.ACT }}  
        uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 2

      - name: Install packages from renv.lock (local, no cache)
        if: ${{ env.ACT }}  
        run: |
          renv::restore()
        shell: Rscript {0}
        
      - name: Run workflow
        run: |
          targets::tar_make(dplyr::starts_with("ihtm"))
        shell: Rscript {0}
        
      - name: Deploy report
        run: |
          targets::tar_make(rrr_evaluation_report_html_2023)
        shell: Rscript {0}
        